### ISSUE TITLE
Spike monitoring and logging solutions 

### ISSUE THREAD

**Issue by markyjackson-taulia** [heptio/java-prototype#13]
Based off the meeting. Kindly assigned to me

**Comment by lypht** [comment]
Once the dockerfile is merged, we will need to add one additional in-line argument for the logging agent to the final CMD: `-javaagent:${WORKDIR}/agent/<monitor>.jar`, when `monitor` can be the flavor of the month: newrelic, splunk, sysdig, prometheus, etc.

**Comment by markyjackson-taulia** [comment]
I’m going to make a few monitoring side cars this weekend. I will get you the details

**Comment by kris-nova** [comment]
any update on this? anything I can help with?

**Comment by markyjackson-taulia** [comment]
I made a mistake with my commit this morning, failed to see the sign off required. I will get that fixed and get this back in

**Comment by markyjackson-taulia** [comment]
This may best be reassigned
