### ISSUE TITLE
Containerize java-prototype

### ISSUE THREAD

**Issue by lypht** [heptio/java-prototype#15]
- [x] Write and test initial Dockerfile locally
- [x] Push to private repo
- [x] Pull from private repo with credentials to test image
- [x] Create build process
- [x] Document build steps
- [x] Automate build process with shell script or fancy CI

**Comment by lypht** [comment]
Build steps require a GCP project to facilitate generating a private image; any merge to `master` will subsequently create a new image.  @kris-nova can you create a GCP project and grant rights to my user so that I can finalize the CI?  TIA

**Comment by kris-nova** [comment]
ah yes - but can we use ECR?

**Comment by lypht** [comment]
Shouldn't be a problem.  The cloudbuild.yaml can remain, as it's only relevant for GCR, and won't impact other registries unless invoked, but might still be helpful for folks using GCP.  I'll add an ECR builder in a new PR.
